### PR TITLE
Add doze to display and Notification Ticker/heads-up disable

### PR DESCRIPTION
**Pull request by xlxfoxxlx**
With these we are going to need the doze commits tested on all devices, and @MZO9400 and other one plus guys i would need you to make sure your doze commits are up to date with these, https://github.com/AOSP-JF-MM/platform_device_oneplus_oneplus3/commits/aosp-7.1.2/doze or it will still be in main settings and not in display.

### CODE REVIEW

**Comment by xlxfoxxlx** [comment]
the way doze is set up is if it has the normal doze package(nexus/pixel) it will show the switch in display, if it is a one plus device or devices that use "com.cyanogenmod.settings.doze" package then it will show the preference to take you to doze options in display, and if the device doesn't support doze at all then it wont display anything.

**Comment by MZO9400** [comment]
Awesome! Good work. I'll test this once I come back hone from my vacation

_Sent from my OnePlus ONE A2003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CheckYourScreen** [comment]
@B--B tested on onyx, testers reported its working fine.
Did anyone else test it out? @MZO9400 @smeroni68

**Comment by smeroni68** [comment]
Hi mate, until @B--B will not include the changes... I can't test... and Mzo is in vacation...

**Comment by B--B** [comment]
Had no time to test yet sorry, had to merge the whole July release into sources, rebase my gemini kernel and update all my tc, in addition launcher3 was crashing with rotation enabled, so had to port all the missing fixes...

**Comment by smeroni68** [comment]
No problem guys... we have many stuff to follow... and need time...

**Comment by CheckYourScreen** [comment]
Should i merge it or leave it as it is(in case you havent compiled a build with this pull request)?
I need to release first build on xda, its working fine as reported by testers. 
What say?
EDIT: Merged. 🙄

**Comment by B--B** [comment]
Ship it, I haven't tried yet on Gemini but it's my problem, I  don't see the reason to keep all these good things pending just because I had no time yet to test them and fix my device tree if everything works fine for all other devices :) gemini users will have this feature next month, no problems for me :)

**Comment by smeroni68** [comment]
Well done mate...

**Comment by CheckYourScreen** [comment]
@B--B few feature requests are still pending like Network Traffic indicator and Soft Nav keys/HW keys switch. You can take ref. from Tesla for Soft/HW keys switch just in case. :)
I'll do whatever i can and make pull requests first.

**Comment by smeroni68** [comment]
@CheckYourScreen perfect... as already sayd, if you all can prepare pull commits for the features, would be more easy (as @xlxfoxxlx have done). Free time is the problem... and merging activities of new releases take time to complete, resolve conflicts and test... thanks guys, really appreciated your efforts to help integration of features in the best way possible.

**Comment by B--B** [comment]
Gemini up to date, tomorrow my testers will be happy...!
Jf not done yet
Thanks for your hard work guys :)

**Pull request merged**
